### ISSUE TITLE
Taxonomy Editor - Requirement Analysis

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#1]
### What

This taxonomy editor will have the following requirements:
- [ ] Creation of a backend for parsing taxonomies
- [ ] Implement CRUD of elements in a taxonomy 
- [ ] Provision for quick search of a component
- [ ] Build hierarchy visualizations for taxonomies
- [ ] Implementing validation of a taxonomy modification

These requirements will be implemented iteratively, and this issue will be updated after each feature implementation.

Any other major requirements will be added, after consulting with other taxonomy contributors. 
Any major workflows followed by contributors for editing taxonomies will be investigated and requirements related to the workflow will be added.

Ideas and contributions are welcome!

![Dataflow](https://user-images.githubusercontent.com/25586296/177000565-c7dcb211-0b76-4845-9f5e-6ef9f463a1be.png)

### Part of

**Comment by alexgarel** [comment]
Project is now on it's way we can close this.
