### ISSUE TITLE
Add autocomplete for language codes in frontend

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#107]
Currently, the frontend has a dialog boxes which have a free TextField component for taking input of a language code. These dialog boxes are present in `search/SearchResults.jsx`, `allentries/index.jsx` and `editentry/ListTranslations.jsx`. 

This is not ideal since from a UX standpoint, since it requires the user to search the list of ISO-6391 codes and figure out the two-letter language code for input.

Instead, an [MUI autocomplete drop-down](https://mui.com/material-ui/react-autocomplete/) menu with all the languages must be created. Upon selection of the language, the corresponding language code must be used for other parts of the code which rely on it.

**Comment by shubham-1806** [comment]
Hey I would like to work on this can you assign this issue to me

**Comment by aadarsh-ram** [comment]
@shubham-1806 Sure!
