### ISSUE TITLE
Improve dev setup instruction

### ISSUE THREAD

**Issue by alexfauquette** [openfoodfacts/taxonomy-editor#114]
I followed the docker setup instructions, up to that point:

> The react application is exposed at: http://ui.taxonomy.localhost:8091
>
> The API is exposed at: http://api.taxonomy.localhost:8091
>
> You can also access the neo4j admin ui at http://localhost:7474/browser/

The http://172.18.0.4:3000/entry is working. The two other ones do not

- For the fronted instead of http://ui.taxonomy.localhost:8091/ it seems to be http://172.18.0.4:3000/
- For the API I did not find how to fetch it

**Comment by aadarsh-ram** [comment]
@alexfauquette I am not sure why there's this issue. Maybe @alexgarel can shed some light?

**Comment by alexgarel** [comment]
@alexfauquette are you on Mac ? On linux everything ending up in .localhost goes to 127.0.0.1.
I though it was the case for other platforms as we also use it for openfoodfacts-server.

What does `ping -4 ui.taxonomy.localhost` do ?

http://172.18.0.4:3000/entry is not a predictable address (will change with every docker container).

My nginx setup is based on the use of ui. and api.

We may need to find a solution for mac users.

**Comment by vedant-z** [comment]
May I try this?

**Comment by alexgarel** [comment]
@vedant-z do not hesitate :-)

**Comment by alexfauquette** [comment]
Just remember that I tried to set up this project last week-end and it worked nicely 👌

Except if you use this issue to track some improvements, it can be closed. Congrats on the infra/set up improvements 👍
