### ISSUE TITLE
Insecure request to API

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#138]
### What

> Mixed Content: The page at 'https://ui.taxonomy.openfoodfacts.net/allergens/testaadarsh/entry/en:gluten' was loaded over HTTPS, but requested an insecure resource 'http://api.taxonomy.openfoodfacts.net/allergens/testaadarsh/entry/en:gluten'. This request has been blocked; the content must be served over HTTPS.

The request to the API works over HTTPS.

### Steps to reproduce the behavior:
1. Create a new project on any taxonomy
2. Click on any existing entry for editing
3. See error

### Expected behavior
All translations, children, parents etc, of the entry, must be rendered.

**Comment by alexgarel** [comment]
The reason is that the nginx on docker side is proxying requests already proxied by our nginx revered proxy, and we loose scheme.

I had to hard code it in the conf, since I didn't find any way to read incoming header on nginx (and in dev, I need it set to http)

**Comment by alexgarel** [comment]
There was also a parameter to add to uvicorn so that it takes into account the proxy headers: [FORWARDED_ALLOW_IPS](https://www.uvicorn.org/settings/#http)
