### ISSUE TITLE
User should be able to close project without exporting it

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#139]
### What
A user might want to abandon a project, and we should give him the ability to close it.

It does not remove the project from the database, it just changes the status.

It would be also nice to be able to re-open a closed project.

**Comment by diivi** [comment]
@aadarsh-ram is the backend for closing and re-opening, both, done? I think you mentioned it in one of the meetings.

**Comment by alexgarel** [comment]
@Jagrutiti can you do the backend part for it ?

Frontend is on the go at #222

We could change current API to be able to:

1. change project status (setting to abandoned, or open (re-opening a projet))
2. list project by status (but default list project API should list opened project, as it's the case now)
3. remove a project (really remove it from database), it a different API from status change. It have to use the DELETE http action.

**Comment by aadarsh-ram** [comment]
@Jagrutiti @alexgarel 
> We could change current API to be able to:
> 
> 1. change project status (setting to abandoned, or open (re-opening a projet))
> 2. list project by status (but default list project API should list opened project, as it's the case now)

PR #152 has already been merged for points 1 and 2.

> 3. remove a project (really remove it from database), it a different API from status change. It have to use the DELETE http action.

An endpoint for point 3 must be made.

**Comment by Jagrutiti** [comment]
> An endpoint for point 3 must be made.

Thank you for for you comment @aadarsh-ram. Will work on it.
