### ISSUE TITLE
Export to GitHub not working

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#144]
### What
Export to GitHub button throws a "Unable to export" error. 

### Steps to reproduce the behavior:
1. Go to export page in a project
2. Click on 'Create Pull Request'
3. See error

### Expected behavior
Needs to give a PR link.

**Comment by aadarsh-ram** [comment]
@alexgarel Is there any issue with the personal access token for Github? Please do check it out.

**Comment by alexgarel** [comment]
@aadarsh-ram the response says: "The Github branch already exists!"

And in the log we only have: 
```
taxonomy_api_1       | INFO:     89.3.192.83:0 - "GET /allergens/test_alex2_allergens/githubexport HTTP/1.0" 500 Internal Server Error
```

I will regenerate a github token to be sure.

**Comment by aadarsh-ram** [comment]
Fixed by changing to new Github token and container fix
