### ISSUE TITLE
Only show some languages in interface

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#154]
### What

Currently we display every language on every entries in the taxonomy editor.

This is really cumbersome as one might only want to eg. translate in Polish from english and maybe spanish.

### Proposed solution

On an entry, only translations in a selected list of languages are displayed. 

A dropdown makes it possible to shown languages. 
This parameter is persisted in local storage, so that if I come back, it's still there.

At any moment I can display a language (maybe because I wont to see how it's handle there) then hide it again… always through this same "displayed language list".

If I add a language ([+] button next to "Translations"), and add an entry for currently not displayed language, it is automatically selected for display.

Note: The main entry language is always displayed, to avoid perception that a page is empty.

**Comment by WaqarTabish2807** [comment]
Hey Alex :))

There is always an issue as "Failed to fetch" in the editor. Can you please help me with it?
