### ISSUE TITLE
Add route for fetching parsing errors for a project

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#156]
During parsing of a taxonomy, all the parsing errors are stored in a separate node with the label "ERRORS" (See function over [here](https://github.com/openfoodfacts/taxonomy-editor/blob/main/parser/openfoodfacts_taxonomy_parser/parser.py#L444)). For the frontend to display the same, these errors need to be accessible through the Taxonomy Editor API.

So, the following needs to be done to enable support to the frontend:
- A function with a neo4j query to fetch parsing errors for a particular project, must be created in [entries.py](https://github.com/openfoodfacts/taxonomy-editor/blob/main/backend/editor/entries.py).
- Add a GET route (maybe `/errors`) in [api.py](https://github.com/openfoodfacts/taxonomy-editor/blob/main/backend/editor/api.py) and it must call the above function and return the results.

**Comment by diivi** [comment]
I have started working on this. Please assign the issue to me

**Comment by alexgarel** [comment]
I suggest naming the route "/parsing_errors" as those are parsing errors.
