### ISSUE TITLE
Find a better UX to submit changes

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#162]
Currently as we modify an entry, we have to hit the "submit" button to send changes to the server.

This is not obvious for the user:
* there is no visual clue for this
* the submit button is down the page, not easy to reach

We should discuss here better alternatives and implement it.

**Comment by alexgarel** [comment]
A simple way could be to display the submit button in the top bar, with a very visible color / layout, and display it only if some changes happens on the page. (but is it simple to implement ?). We could add an animation after each changes to make the button wiggle a bit.

An alternative is to submit changes as they happen on the interface, without any need to submit. Though this might make it more difficult to run validations.

**Comment by diivi** [comment]
Another good to have might be a confirmation popup from the browser (an alert) on the window unload/reload events, that tells the user they have unsaved changes.

**Comment by aadarsh-ram** [comment]
@diivi @alexgarel An initial idea was to keep a red "unsaved changes" snackbar very visibly on any edits. After the submit button has been clicked, the snackbar changes to "Changes were saved!". The confirmation popup will also be a fallback for the user to save any edits, before navigating to a different entry.

**Comment by alexgarel** [comment]
yes, @aadarsh-ram what you describe, with a sticky bottom "unsaved changes" is the best option. (if it's not too hard to do with CSS, it's perfect)

**Comment by WaqarTabish2807** [comment]
A 'Draft' feature could also be introduced where the user could see their unsaved changes and also provide them with an option to save it as a draft if they want to come back and edit it later.

Or, Providing a 'Preview' feature, where users can see how the changes they made would reflect on the page, can also be beneficial.

**Comment by alexgarel** [comment]
Preview seems a bit too much here, changes are very simple.

Also we have plans to be able to roll-back changes : 
- #58

**Comment by MERAKISHRUTI** [comment]
if user does not feed proper information then submit function will not work and red pointer points where they give us wrong information or empty info.

**Comment by alexgarel** [comment]
@MERAKISHRUTI appart from really silly changes, we could also accept changes, but display errors (see issues dealing with it) eventually blocking export until they are fixed.

**Comment by aadarsh-ram** [comment]
Resolved via #224
