### ISSUE TITLE
create project: feedback if you use hyphens in branch name

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#168]
Adding hyphens and special characters is not possible in branch nam, due to limitations of Neo4J labels. 
We require a feedback mechanism for indicating users about the name in the frontend.

**Comment by NihalRadhakrishna** [comment]
@alexgarel  can I work on this. I was thinking of showing error message like this
![image](https://user-images.githubusercontent.com/91626278/218311434-e9a1bab8-e96f-455d-bcb4-f766a616f0b7.png)

**Comment by alexgarel** [comment]
Yes, please do @NihalRadhakrishna.
Thank you for showing an example.
