### ISSUE TITLE
add a help page to explain what the tool is for and the github workflow

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#169]
read https://wiki.openfoodfacts.org/Global_taxonomies
https://wiki.openfoodfacts.org/GSOC_2022_-_Taxonomy_editor
also read as much as you can on this project

Ask questions if you need :-)

**Comment by WaqarTabish2807** [comment]
Hey @alexgarel and @aadarsh-ram, I am adding the doc file here in which we'll address the comment and curate the help page. Thanks. 

https://docs.google.com/document/d/1VNxdhz9u2iM3yIFUcdhq-_raULEpoKSjNDNKGI7j2yk/edit#

**Comment by alexgarel** [comment]
I @WaqarTabish2807 thanks for trying to tackle this. But a lot of the thing you say are not accurate. Where did you get the information from ? You need to understand the project better first.

**Comment by alexgarel** [comment]
https://blog.openfoodfacts.org/en/news/on-taxonomies is also a good 
and https://blog.openfoodfacts.org/en/news/how-i-helped-open-food-facts-to-better-recognise-ingredients-in-my-country

**Comment by NihalRadhakrishna** [comment]
I would like to work on this issue.

**Comment by alexgarel** [comment]
please do @NihalRadhakrishna :-)

**Comment by mahak24342** [comment]
i wanna take up this issue , please assign me this issue

**Comment by alexgarel** [comment]
@mahak24342 sorry for late notification, but just take any task you want, just tell you do it with a comment :-)
I'm eager to see your PR's. Don't hesitate to come on our slack to discuss if you need.

**Comment by alexgarel** [comment]
This has been done (but can be improved) here: https://wiki.openfoodfacts.org/Taxonomy_editor
