### ISSUE TITLE
Enable uploading a file (instead of getting it from github)

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#170]
### What
Currently we can only choose a taxonomy to be uploaded from github.

This is not practical for development. Add the possibility to upload a file from local computer.

Eventually add a feature flag in the configuration to enable/disable it.

**Comment by WaqarTabish2807** [comment]
Here is my possible solution to it. 

Firstly, we'll need to modify the configuration file for the Taxonomy Editor. which we can get at config/default.json.

In the configuration file, we need to search for the taxonomies section. Here, we'll see a source field set to github by default. To enable uploading a file, we need to make changes to this field to file.

Next, we'll need to add a path field to the taxonomies section. This field should specify the location on our local file system where the taxonomy files will be stored. For example, we could use ./taxonomies to store the files in a directory named taxonomies at the project's root.

Hope it may help divi :))

**Comment by alexgarel** [comment]
@WaqarTabish2807 I'm not really in phase with your solution.

One should simply add a new API point to receive a file upload, and then use the parser.

The github pull already has code to place the file in a tmpdir (cf tempfile module in python). It's very important to use a unique file name as there might be concurrent uploads. We may refactor a bit so that the code is nicely shared for upload and github pull.

Then there is the JS part for the UI, but we may split this ticket in two.

**Comment by alexgarel** [comment]
@diivi if we can move forward on this ? It seems @Jagrutiti is not able to connect to raw.githubusercontent.com and is blocked by this.

**Comment by diivi** [comment]
Will start with the frontend on Monday 👍🏼

**Comment by alexgarel** [comment]
This feature is already there :-)
