### ISSUE TITLE
Overall Architecture and Design

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#2]
## Initial idea
This taxonomy editor will mostly comprise of a decoupled front-end and back-end.

### Backend
- An API for CRUD operations will be constructed
- This API will interface with the frontend, to perform operations on the DB.
- A separate parser script (part of the backend), would be able to convert .txt files to a Neo4J DB.
- A separate converter script (part of the backend), would be able to convert the updated Neo4J DB to the .txt format.
- **Tech stack** - Python + FastAPI (currently used)

### Database
- Currently, the taxonomy file is being stored in a Neo4J database.
- Appropriate relationships (edges) are constructed to maintain order and parents of nodes.
- The parser would be able to parse a taxonomy and construct the Neo4J database from scratch.
- **Tech stack** - Neo4J

### Frontend
- Taxonomy structure using a suitable visualization, will be displayed.
- CRUD of components in a taxonomy in the visualization will be allowed here.
- Searching of a component in a taxonomy will be implemented here.
- Existing implementations for visualizing DAG's will be attempted to be integrated here.
- **Tech stack** - React (not finalized)

Any other features required will be added to this issue.
Other ideas regarding this architecture are also welcome!

**Comment by alexgarel** [comment]
@aadarsh-ram I suggest also looking at elasticsearch or other equivalent database, as search options might be richer than in mongodb (and searching the taxonomy is quite an important feature).

**Comment by alexgarel** [comment]
> where one node has muliple parents

Simply look where two occurrences of "<" happens on succesive lines.

With vscode for example you can do a search for the regexp `^<.*\n<`

Eg in ingredients.txt:

```
<en:caramel syrup
<en:sugar
en:caramelised sugar syrup, caramel sugar syrup

...

<en:soya lecithin
<en:sunflower lecithin
en:soya and sunflower lecithin

...

<en:gelatin
<en:beef
en:beef gelatin
```

there are approx 430 in ingredients.txt

**Comment by aadarsh-ram** [comment]
Ah thanks @alexgarel! I got a little confused seeing all the different taxonomy stuctures.

**Comment by aadarsh-ram** [comment]
@alexgarel @stephanegigandet I had a few doubts regarding the taxonomy structure. 
- Do nodes with "multiple parents" come right after their parents have been initialized? 
- Can those types of nodes appear anywhere in the taxonomy? 
- Are those "multi-parent nodes" initialized only after their parents have been initialized?

**Comment by stephanegigandet** [comment]
Hi @aadarsh-ram ,

You mean how to build the taxonomy structure from the source .txt files ?

It's poorly documented, it's done by this function: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Tags.pm#L786

There are different phases:

Phase 1 : all entries and their translations are read

Phase 2 : we compute extra synonyms for entries (there's a kind of recurrence system, if there is an entry "yoghurts" with a synonym "yogurts", then we will generate extra synonyms for entries like "strawberry yoghurts"

Phase 3 : we compute the hierarchy (finding the parents and children of all entries)

So there is no special ordering in the source .txt file, entries can be in any order. Often they have been grouped by editors.

That's true also for multi-parent notes, they can be anywhere in the source file.

**Comment by aadarsh-ram** [comment]
> @aadarsh-ram do you know that we also generate a json for taxonomies ?
> 
> It's well hidden: its at `https://world.openfoodfacts.org/data/taxonomies/<taxonomy-name>.json` and `https://world.openfoodfacts.org/data/taxonomies/<taxonomy-name>.full.json`

This is just perfect @alexgarel. I had thought of creating a structure like this (properties, children, parents) from the taxonomy and storing each product has a document in ES. Each collection in ES would correspond to the entire taxonomy. Does this make sense?

> That said I don't know which script generates / update them (@stephanegigandet ?)

As far I can see, the `scripts/build_tags_taxonomy.pl` script is used for building the sto file. `scripts/sto_to_json.pl` converts the sto file to JSON. But, there seems to be no script for JSON to sto conversion. @alexgarel @stephanegigandet if there is a Perl script for that, please let me know.

**Comment by aadarsh-ram** [comment]
Regarding the scripts `build_tags_taxonomy.pl` and `sto_to_json.pl`, is it possible to run them without installing the whole server? I tried running the script standalone, and I didn't run. If there's a way, it would be pretty great to just use the script from my proposed server.

**Comment by stephanegigandet** [comment]
> Regarding the scripts `build_tags_taxonomy.pl` and `sto_to_json.pl`, is it possible to run them without installing the whole server?

The easiest is to install the server with docker, as it will install all the dependencies.

You can run them standalone, but you will have to install all the required Perl modules.

**Comment by stephanegigandet** [comment]
> As far I can see, the `scripts/build_tags_taxonomy.pl` script is used for building the sto file. `scripts/sto_to_json.pl` converts the sto file to JSON. But, there seems to be no script for JSON to sto conversion. @alexgarel @stephanegigandet if there is a Perl script for that, please let me know.

In fact build_tags_taxonomy.pl builds the JSON version of the taxonomy directly (in the build_tags_taxonomy() function of Tags.pm). But that version is kind of a subset of the taxonomy data.

If you use sto_to_json.pl on the .sto of the taxonomy, you will get everything that is currently loaded in memory in the backend (in particular it includes all generated synonyms for all entries)

We never needed a json_to_sto.pl but it should be straightforward to create.

**Comment by alexgarel** [comment]
@aadarsh-ram, not 100% sure, but my opinion would be to have a python parser. I don't think it's that hard.
But as stephane said, you can also use the docker of product opener and run the script. You could also try to extract relevant code in perl and run them in a docker. I just fear those approach would take you more time than writting a parallel implementation in python (you can use same structure as perl code. If you need, after you try to understand how the parsing work we can do a quick review, (even on meet) to explain the part that you're not sure to get.

> But, there seems to be no script for JSON to sto conversion.

No, and you don't need to create sto. You need to create `.txt`. The source file for taxonomies is the` .txt`. The `.result.txt` is just a by-product and the `.sto` is an internal storage (like a pickle in python).

**Comment by aadarsh-ram** [comment]
> The easiest is to install the server with docker, as it will install all the dependencies.

@stephanegigandet, I was able to do that and it worked perfectly! I was able to generate a JSON from the sto files present in the "taxonomies" folder.
 
> @aadarsh-ram, not 100% sure, but my opinion would be to have a python parser. I don't think it's that hard.
> But as stephane said, you can also use the docker of product opener and run the script. You could also try to extract relevant code in perl and run them in a docker. I just fear those approach would take you more time than writting a parallel implementation in python (you can use same structure as perl code. If you need, after you try to understand how the parsing work we can do a quick review, (even on meet) to explain the part that you're not sure to get.

@alexgarel I think I might take more time in writing a Python parser, since that would require understanding the Perl code and reproducing it exactly. Instead, I was hoping to use the two scripts that I had mentioned standalone in my Python server, since it essentially operates only on the taxonomy files (atleast that's my understanding).

> No, and you don't need to create sto. You need to create `.txt`. The source file for taxonomies is the` .txt`. The `.result.txt` is just a by-product and the `.sto` is an internal storage (like a pickle in python).

Oh okay. So, I might need to write a parser for conversion from JSON to .txt, in order for Product Opener to use it. Is my intuition right?

> I had thought of creating a structure like this (properties, children, parents) from the taxonomy and storing each product has a document in ES. Each collection in ES would correspond to the entire taxonomy. Does this make sense?

@alexgarel @stephanegigandet should the above method be enough for storing the taxonomies in a database?

**Comment by alexgarel** [comment]
For the ES part, by collection, do you mean "index". Yeah sure I think having an index, with given data should ok.

* I will not only have the parent field, but also a children field, an ancestors field and a descendants field. This will enable for searching in multiple ways. An easy way to get those info is to feed you entries in a library like networkx.
* Don't forget to specify an id : the dict key in the json (if not ES will create a random one, which is not nice in this case)
* consider if you need a specific schema (ES will automatically create one for you, but that's not always adapted)

**Comment by alexgarel** [comment]
> Oh okay. So, I might need to write a parser for conversion from JSON to .txt, in order for Product Opener to use it. Is my intuition right?

Yes. Hopefully json to txt is far easier to write.

The problem, if we want to generate a txt file that is easy to review in github, is that we should always get same ordering.

I would advocate to have a predictable ordering.

I imagine ordering on depth (longuest path from top) of element and then (for element of same depth), lexical order of entries (language prefix included). But I'm really not sure because it would mean that on changing parents of an element, all it's descendant might change position in the file !

So finally lexical ordering  on entry id might be the best option, although it does not seems the best for a human reader.

It wont match current order, but we could do a first commit in github where we completely change current ordering to respect this new ordering (think txt -> json -> txt then commit).

Another (less attractive to me) option, is to track current .txt ordering in the json, keep it, and always add new entries at the end of the file.

**Comment by alexgarel** [comment]
To keep comment, best approach, I think, is to keep lines before the entry in a "head"  (like tail in html, the other way around).

Combined with positions of element it makes it easy to reconstruct original file without loosing information. Although you have to handle the case of removed items (either transfer it's head to next element, or make it a blank line to keep comments).

**Comment by aadarsh-ram** [comment]
@alexgarel @stephanegigandet Thanks for all your inputs! As @alexgarel mentioned, I think the best way to proceed forward is to write the "txt to JSON parser" and "JSON to txt converter" in Python from scratch.

I will follow this plan to write the parser and the converter:

Parser:
- Add all nodes (Without info)
- Serialize nodes wrt the taxonomy file
- Functionality for adding new nodes and changing serialization order accordingly (will try to use @stephanegigandet's suggestion of adding under its first parent)
- Functionality for removing nodes and changing serialization order accordingly
- Add all subattributes (info, comments, children, parents etc)
- Add new nodes and computing subattributes
- Add stopwords, synonyms etc
- Creating redundancies (ancestors, descendants etc) for faster searches

Converter:
- Use serialized JSON to bring back the txt file format with comments

I will implement these sections iteratively and test it out. After the parser and converter works, I'll look into storing this JSON in ElasticSearch. @alexgarel @stephanegigandet does this sound good?

**Comment by alexgarel** [comment]
Sounds good to me.

**Comment by alexgarel** [comment]
We are now implementing :-)
