### ISSUE TITLE
Decide the way to store tags and tags_ids

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#20]
There is a limitation to Neo4J: it does not stores nested values in fields (it flattens it to a string).

As [stated in the dev documentation](https://neo4j.com/docs/getting-started/current/graphdb-concepts/#graphdb-properties):

> The value part of a property:
> * Can hold different data types, such as number, string, or boolean.
> * Can hold a homogeneous list (array) containing, for example, strings, numbers, or boolean values.

Now we should bare in mind that we want to be able:
* to find nodes by lc:tagid (to search parents)
* to display tags / tagids by language

**Comment by alexgarel** [comment]
@aadarsh-ram, we talked with @BryanH01 and I see two main options (I concentrate on tags_ids, but it's the same for tags):

* store in a single list:  
  ```
  tagids: ["en:thing", "en:other", "fr:truc", "fr:autre-truc"]
  ```

* store with one field per language:
  ```
  tagids_en : ["thing", "other"]
  tagids_fr: ["truc", "autre-truc"]
  ```

Options 2 seems better to me. It will bring better performance / storage efficiency. It's also more in line with entry display (you don't have to re-generate the per language lists).

Only draw back would be to search on all language at the same time, but:
- we won't do this to search tags for a functional operation: we always target a language
- we may do it for the taxonomy editor interface, but in this case we may want to search more fields as well, and it is still feasible (number of language is not that big), or we could even add a "tokens" field to add every tokens we want to be able to search on.

**Comment by aadarsh-ram** [comment]
@alexgarel I agree. Option 2 is more elegant and easier to work with. So, this means that the stopwords and synonyms blocks also   need to follow the same format (tagids_en, tags_en) instead of the [previous format](https://github.com/openfoodfacts/taxonomy-editor/blob/main/backend/sample/test.json#L33) that you proposed.

**Comment by alexgarel** [comment]
Yep, although I don't think this kind of modeling really fits in a json schema… but you can add just "en" and "fr" maybe.

**Comment by aadarsh-ram** [comment]
> Yep, although I don't think this kind of modeling really fits in a json schema… but you can add just "en" and "fr" maybe.

I think writing "tagids_LC" in the JSON schema might be intutive to understand. For more clarity, the test JSON file would have "tagids_en" and "tagids_fr" too.

**Comment by aadarsh-ram** [comment]
@alexgarel As per our current schema, the "properties" key is a list of dictionaries, where each dictionary corresponds to one property. Would it be ideal to store all those dictionaries as a string, and interconvert whenever necessary?

**Comment by alexgarel** [comment]
@aadarsh-ram good point, I was returning on the issue for the same reason :-)

I think we should do the same as for tags for properties and flatten. Properties are important to query because at some point we may want to find the entries corresponding to agribalyse for example, or the one that have a wikidata entry.

So I would add properties one by one, using the prop_ prefix.

That is 

```
wikidata: P00045
agribalyse_id: 1234
```

should be translated:

```
prop_wikidata: P00045
prop_agribalyse_id: 1234
```

**Comment by stephanegigandet** [comment]
@alexgarel Property values are language specific though (the ones that are not language specific, we use the "en" language).

e.g.

```
en:Fair trade
xx:Fair trade
wikidata:en:Q188485
opposite:en: en:non-fair-trade
description:en:Fair trade is an arrangement designed to help producers in developing countries achieve sustainable and equitable trade relationships. Members of the fair trade movement add the payment of higher prices to exporters, as well as improved social and environmental standards. 
description:de:Als Fairer Handel (englisch fair trade) wird ein kontrollierter Handel bezeichnet, bei dem die Erzeuger für ihre Produkte einen Mindestpreis erhalten, der von einer Fair-Trade-Organisation bestimmt wird. Damit soll den Produzenten auch bei niedrigeren Marktpreisen ein höheres und verlässlicheres Einkommen als im herkömmlichen Handel ermöglicht werden.
description:hu:A méltányos kereskedelem olyan irányított kereskedelem, amely hangsúlyt helyez arra, hogy a harmadik világbeli termelő megkapja az őt megillető pénzt a terményéért.
description:es:El comercio justo es una forma alternativa de comercio promovida por varias ONG (organizaciones no gubernamentales), por la Organización de las Naciones Unidas y por los movimientos sociales y políticos (como el pacifismo y el ecologismo) que promueven una relación comercial voluntaria y justa entre productores y consumidores.
description:fr:Le commerce équitable est un système d'échange dont l'objectif est de proposer une plus grande équité dans le commerce conventionnel, voire une alternative à celui-ci, basée notamment sur la réappropriation des échanges marchands par ceux qui les pratiquent.
description:nl:Eerlijke handel is internationale handel die gericht is op duurzame ontwikkeling in ontwikkelingslanden, met name bij de export van zulke landen naar rijkere westerse landen. Fair trade duidt op een streven om boeren voor hun exportproducten een prijs te geven die in verhouding staat tot de werkelijke productiekosten, en niet een prijs die wordt bepaald door de verhoudingen op de internationale markt.
```

We can suffix the property field with the language code.

**Comment by alexgarel** [comment]
See https://github.com/openfoodfacts/taxonomy-editor/blob/06702ceb4519ac0b9627c7c625fe3b33dd312983/backend/sample/test-neo4j.json for a first example.

**Comment by aadarsh-ram** [comment]
Since a way to store tags and tag_ids has been decided, I'll be closing this issue.
