### ISSUE TITLE
Expand all languages by default

### ISSUE THREAD

**Issue by diivi** [openfoodfacts/taxonomy-editor#202]
### What
- All languages in an entry are collapsed right now by default. Make them expanded
![image](https://user-images.githubusercontent.com/41837037/214480443-e22fdc29-58cd-4a8e-adb1-54785b3e55f1.png)
- Save collapsed languages in local storage preferences and only collapse those languages. Something like this is already done for `shownLanguages` refer [this file](https://github.com/openfoodfacts/taxonomy-editor/blob/5c9df2e7118d574f2c526be81cee6fdb4317b5fc/taxonomy-editor-frontend/src/pages/editentry/ListTranslations.jsx#L166)

I'll do this if there are no takers after a few days.

```[tasklist]
### Tasks
```

**Comment by AnshMasand** [comment]
hello, Id like to work on this issue

**Comment by diivi** [comment]
Sure, go ahead. Ask questions in the slack channel #taxonomy-editor if you get stuck!

**Comment by urek696969mazino** [comment]
hello i would this to solve this issue

**Comment by alexgarel** [comment]
@urek696969mazino if @AnshMasand do not react until the end of this week, let's do it. Otherwise there are other issues.

**Comment by AnshMasand** [comment]
@urek696969mazino you can work on it I have removed my assignment.

**Comment by mahak24342** [comment]
i wanna take up this issue , please assign me this issue

**Comment by divyamsingh4444** [comment]
kindly assign me this issue

**Comment by aapatil2004** [comment]
Hey can i solve this issue

**Comment by alexgarel** [comment]
@aapatil2004 this is an old issue which is not up to date, I'm closing it !
