### ISSUE TITLE
use FastAPI background tasks for long running parsing

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#206]
### What
- before parsing we create the project with  status : initializing
- in the project view if it’s still initializing, we ask user to wait

### Why
- It's not currently possible to import the `labels` or `categories` taxonomy

### Part of
- #167

**Comment by alexgarel** [comment]
@diivi I believe you are on it, right ?

**Comment by diivi** [comment]
I don't have context about the 3rd point (UX to reopen a project), but the rest, yes.

**Comment by alexgarel** [comment]
@diivi I think it's an error of indentation from the previous issue, it's a different task ! (removed)

**Comment by alexgarel** [comment]
This is now done.
