### ISSUE TITLE
Comments box should respect line return + avoid '#'

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#209]
- make ‘#’ automatically handled (do not show them in the front, let add them when saving)
- make the text box larger
- make it respect “\n” as lines

**Comment by harivamsi9** [comment]
Hey can i do this?

**Comment by alexgarel** [comment]
@harivamsi9 if no one is on a bug, just signal you are taking it … and go :-)

**Comment by mahak24342** [comment]
i wanna take up this issue , please assign me this issue

**Comment by alexgarel** [comment]
To explain point 1 and 3:
we have a comment field which contains something like:

```
# this is a multi
# line
# comment
```

Currently this is displayed as
```# this is a multi # line # comment```

So we should display it as:
```
this is a multi
line
comment
```

This may mean doing a transformation before displaying and before saving:
- before displaying: stripping the "#", replacing '\n' by '<br>\n' (?)
- before saving: replace <br>\n or <br> by \n, add '#' as first char on each line
(but it may also be implemented otherwise).

IMO it should be handled client side.

**Comment by eeshaanSA** [comment]
Do you mean the Comment box in this section? 
So as far as I have understood, any new comments we add with the taxonomy editor (multi line comments), they are still parsed as a single line in the taxonomy.txt file?
![image](https://github.com/openfoodfacts/taxonomy-editor/assets/100678386/bbbd31fe-aea1-4af9-a07f-2187f5739203)

**Comment by alexgarel** [comment]
yep, this one box :-)

**Comment by aadarsh-ram** [comment]
> Do you mean the Comment box in this section? So as far as I have understood, any new comments we add with the taxonomy editor (multi line comments), they are still parsed as a single line in the taxonomy.txt file?

Comments in the taxonomy editor are separated by newline characters. Any line not ended with a newline character, will be considered as one comment. (it's a similar system to python, if that makes sense)

In the screenshot, the description is a very long comment, which will be treated as a single comment. On the other hand, each translation has a newline associated with it, so they are multiple comments.

**Comment by alexgarel** [comment]
This one is outdated.

We finally conclude that comment are at the property level.

We need to have a general reflexion on how to display comments in the interface, and eventually make them editable.
