### ISSUE TITLE
feat: Use load animation

### ISSUE THREAD

**Issue by NihalRadhakrishna** [openfoodfacts/taxonomy-editor#227]
### Problem
When user clicks on open existing project button or edit project button it shows "loading..." text.

### Proposed solution
We can add loading animation using mui circular progress component.

### Mockups
![image](https://user-images.githubusercontent.com/91626278/218259987-2f95374c-4d4b-435c-adac-fdd0c6389d2c.png)

### Part of
- #

**Comment by NihalRadhakrishna** [comment]
Something like this...
![image](https://user-images.githubusercontent.com/91626278/218260265-128ae0e3-d6fc-43bd-a620-d6c1f955beed.png)

**Comment by aashimawadhwa** [comment]
I would like to take this issue.

**Comment by alexgarel** [comment]
@aashimawadhwa just tell you gonna take it and it's yours :-) (if no one already signal he is on it).

**Comment by NihalRadhakrishna** [comment]
@aashimawadhwa can I pls take this issue since I opened it. I've already got it working on my local setup.
