### ISSUE TITLE
Blank page appears when edit button is clicked in the root nodes page.

### ISSUE THREAD

**Issue by NihalRadhakrishna** [openfoodfacts/taxonomy-editor#234]
### What

Error occurs when we want to go to edit entry page.
Uncaught TypeError: duplicateNode[key].forEach is not a function
### Steps to reproduce the behavior:
1. Go to any existing project and click on edit button.
2. Click on edit button in the root nodes page.
3. Blank screen appears and when u inspect the page you can see the error in the console.

### Expected behavior

The edit entry page should render without any errors

### Screenshots

![image](https://user-images.githubusercontent.com/91626278/219655698-c8cbef84-df91-42be-ba5c-2e3e0a98a9e6.png)

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Windows 10
 - Platform: Desktop

### Suggested solution
duplicateNode[key] returns an object when we console.log(typeof(duplcateNode[key]). So forEach method cannot be used on it.
We could convert it into an array by using Array.from(duplicateNode[key]).

**Comment by NihalRadhakrishna** [comment]
I would like to work on this issue if others are able to reproduce it.

**Comment by aadarsh-ram** [comment]
@NihalRadhakrishna This error occurs due to a recent PR update related to the Neo4j database. 

@alexgarel Please do clear the database, so that there are no blockers.

**Comment by alexgarel** [comment]
@aadarsh-ram is this already in production also or just stagging ?

@aadarsh-ram maybe write a message on slack, explaining people should `docker-compose down -v` to clear data in their local environment.
