### ISSUE TITLE
Command to import some test data in setup-dev.md outdated

### ISSUE THREAD

**Issue by perierc** [openfoodfacts/taxonomy-editor#262]
![image](https://github.com/openfoodfacts/taxonomy-editor/assets/82757576/d27d19fb-3b57-4c3a-8ed1-361ceb7ab7b5)

The command written in setup-dev.md to import some test data in neo4j using Docker is not working. The `taxonomy_api` container doesn't have the `sample` folder that the command is trying to access.

### Part of
- https://github.com/openfoodfacts/taxonomy-editor/issues/263

**Comment by aadarsh-ram** [comment]
Hey @perierc. The `backend` folder contains the sample folder you're talking about. The `test-neo4j.json` is outdated due to many changes to the schema, and needs to be updated.

For playing around with the editor, you can directly import the `test` taxonomy for now, through the API or UI.

**Comment by alexgarel** [comment]
We will handle it with #225
