### ISSUE TITLE
error while  attempting to edit an entry of the taxonomy from root node pages 

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/taxonomy-editor#275]
### What
There seems to be an error while i'm attempting to edit a taxonomy from the taxonomy editor (https://ui.taxonomy.openfoodfacts.net/states/editstostates/entry). Here is the error. 

```
entry:1 Failed to launch 'en:to-be-checked' because the scheme does not have a registered handler.
```

Note that there's a work around. If you search for the node you can then edit it correctly. We should have the same components for both use cases.

### Part of
-

**Comment by alexgarel** [comment]
fixed by https://github.com/openfoodfacts/taxonomy-editor/pull/284
