### ISSUE TITLE
Add main_language as a property to the entries in neo4j

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#28]
Currently we indirectly have this information through the language code in the id.

But we want to be able to change main language (that is language giving the id) without modifying the id (yet) to make things simpler. (we shall change our mind on this later).

Add a "main_language" property to entries.

- [ ] change documentation and sample
- [ ] change parser

**Comment by alexgarel** [comment]
@BryanH01 I let you close this ticket when you have introduced the property in the parser.

**Comment by BryanH01** [comment]
I added it
