### ISSUE TITLE
Make parsing more performant

### ISSUE THREAD

**Issue by eric-nguyen-cs** [openfoodfacts/taxonomy-editor#289]
## Now

Currently, it takes a few seconds to import some taxonomies and some taxonomies are not parsed before the http requests timeouts.
The parsing step takes too much time

## Goal

Understand why parsing takes so much time to respond and resolve it
- Make the parser faster if possible 
- If not possible, respond to the client asynchronously

**Comment by alexgarel** [comment]
@eric-nguyen-cs it's mandatory to make the client respond asynchronously, (there are huge taxonomies). see #206

But working on parsing performance is also important as I believe there might be low hanging fruit.
