### ISSUE TITLE
Add GET path for finding relationships of a node

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#33]
There is no path for finding relationships (mainly `is_child_of` relationship) for any node. This must be added to compute the immediate parents and children of a particular node. (Will be helpful for the frontend)

**Comment by alexgarel** [comment]
You can either do it with an API or add it to the /entry API ? (maybe with a additional_fields=parents) ?

**Comment by aadarsh-ram** [comment]
> You can either do it with an API or add it to the /entry API ? (maybe with a additional_fields=parents) ?

@alexgarel I think having an additional fields property would make the code a little messy on the "database functions" (entries.py) side, with a lot of conditions. It seemed cleaner to make two different paths `/entry/{entry}/parents` and `/entry/{entry}/children` instead.
