### ISSUE TITLE
Upgrade the UX around error handling

### ISSUE THREAD

**Issue by eric-nguyen-cs** [openfoodfacts/taxonomy-editor#332]
Errors should be fixed before the edition of the taxonomy (they should stop the taxonomy edition)

**Comment by alexgarel** [comment]
@eric-nguyen-cs I'm not sure errors should be fixed.

Right now we only register parsing errors. But the idea was to also register "logical errors" in the future, so maybe we have two types of errors.

**Comment by alexgarel** [comment]
> Right now we only register parsing errors. But the idea was to also register "logical errors" in the future, so maybe we have two types of errors.

I think we could introduce error severity: blocker, major, minor, warning.

Blocker would mean, it must be fixed before being able to edit this taxonomy. If any exists, we should pass the project state to "failed".

Major would disallow taxonomy export (but you can edit it to fix those errors).

**Comment by alexgarel** [comment]
At the end of parsing, if there are errors pass the status to FAILED.

Make only open projects editable in the UX (open a new ticket for that)

**Comment by Piv94165** [comment]
UPDATE :
- at the end of parsing, if there are errors, the status is OPEN but a warning should be displayed in the editor to warn user about the errors

**Comment by alexgarel** [comment]
The part above has been done.
