### ISSUE TITLE
Update Github API calls

### ISSUE THREAD

**Issue by eric-nguyen-cs** [openfoodfacts/taxonomy-editor#349]
- use https://github.com/yanyongyu/githubkit instead of PyGithub for async github calls
- Fix Create Pull request errors
- Keep track of import commit
- When exporting, checkout from that commit

The last two items will ensure that changes between import and export time are automatically merged thanks to git.

**Comment by eric-nguyen-cs** [comment]
Also, fix the export PR: right now, it seems that the file diffs are not working correctly with the correct endpoint we are using. It seems we should directly manipulate the git tree (https://docs.github.com/en/rest/git/blobs?apiVersion=2022-11-28)

**Comment by eric-nguyen-cs** [comment]
Others wins would be:
- be able to reexport a project (for example, after resolving comments on the taxonomy editor project): we could replace the "Create Github PR" button by an "Export to Github" button, that would either create a PR if the branch has not been created yet or create a new commit on the existing branch
- to mark the project as CLOSED or delete it when the PR has been merged

**Comment by alexgarel** [comment]
@eric-nguyen-cs re-exporting would update the branch ?

**Comment by eric-nguyen-cs** [comment]
The goal would be for re-exporting to add a new commit to the branch yes. You would be able to see the new changes in the PR

**Comment by alexgarel** [comment]
That's a cool feature :-)
So one can use the taxonomy editor to fix problems in a PR. I like it :-)

I was also wondering of adding a flag to changed entries to be able to get them quickly in the search. And the link to that would be in the PR comment. I'll open an issue for that.

**Comment by alexgarel** [comment]
> I'll open an issue for that.

#366
