### ISSUE TITLE
Handle 'xx' language for translations edition

### ISSUE THREAD

**Issue by Piv94165** [openfoodfacts/taxonomy-editor#355]
Enhance language display on the frontend for "xx":

Currently, when attempting to display a language, the frontend behavior is incomplete : the "xx" language is not displayed.
To improve this, the goal is to ensure that the 'xx' translation is displayed in all situations as a translation section. This adjustment will enable user to add "xx" translations, which are universal words.

![Image](https://github.com/openfoodfacts/taxonomy-editor/assets/106757110/44156fa3-e891-4e87-8883-b173d8fd757e)

In the taxonomy file, we observe the entry: 'xx:E100'. This signifies that 'E100' is a universal identifier applicable to all languages. Therefore, it is essential to ensure it's displayed in the taxonomy editor to be able to modify it.

**Comment by alexgarel** [comment]
I don't think this is the right approach, see https://github.com/openfoodfacts/taxonomy-editor/pull/354#issuecomment-1898920263
