### ISSUE TITLE
Fix newline character `\r` diff issue

### ISSUE THREAD

**Issue by eric-nguyen-cs** [openfoodfacts/taxonomy-editor#359]
https://stackoverflow.com/questions/5843495/what-does-the-m-character-mean-in-vim (`\r` is displayed as `^M` `in git diff`)
https://en.wikipedia.org/wiki/Newline#Representation
Some taxonomy files have been created in Windows, so their newline character has an extra `\r`. This can be confusing for Git and Github displays newline characters from Windows (`\r\n`) and from Unix. (`\n`) as different in PRs by default: this is a problem for the taxonomy editor that creates files with the Unix newline character (`\n`)

Two fixes seem possible:
- ask reviewers to change their PR settings for each PR they review (seems not to be the greatest user experience)
![Image](https://github.com/openfoodfacts/taxonomy-editor/assets/77902715/7f89bc39-8227-4904-94c0-b60554935b44)
- update all source taxonomy files to have the Unix newline characters (but it may cause conflict for opened PRs on openfoodfacts-server)

**Comment by alexgarel** [comment]
updating taxonomies to use unix newline is the best choice.

**Comment by eric-nguyen-cs** [comment]
Fixed in https://github.com/openfoodfacts/openfoodfacts-server/pull/9749
