### ISSUE TITLE
Update Neo4J query to disallow partial updates

### ISSUE THREAD

**Issue by aadarsh-ram** [openfoodfacts/taxonomy-editor#40]
Currently, the frontend tracks all changes (creation, addition, deletion) on keys and values of a node, and POSTs all information (such as translations, preceding_lines, properties etc) about a node. 

Since, the query only allows partial updates, deleted keys are not tracked in the database. Hence, the update db query has to be changed to allow full updates to a node.

**Comment by alexgarel** [comment]
I don't think this is a very good idea.

I think node id should be recomputed each time, and this should be the last query emitted.
The most simple way is to first do all updates, then recompute id, and if it changed, call a special function to do this update.

I don't know if it is a problem for the ReactApp (id should change url), but the request could either send back a response to trigger the "move", or simply we could ignore it.
