### ISSUE TITLE
Rewordings for exports

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/taxonomy-editor#410]
### What
![image](https://github.com/openfoodfacts/taxonomy-editor/assets/1689815/58e3e598-8278-489c-b214-60ae003d0b1b)

Please check your pull request looks ok, and feel free to add a quick description of your changes.
PR >> Pull Request
A button to close (or reword cancel to close ?)

**Comment by alexgarel** [comment]
@Piv94165 

It's a quick win, and I tihnk it's important to tell the contributor to look at the github PR.
