### ISSUE TITLE
Solve problem of taxonomies extended by other taxonomies

### ISSUE THREAD

**Issue by perierc** [openfoodfacts/taxonomy-editor#414]
For packaging and traces this is not a problem, they are just virtual taxonomies.

So it's a problem only for origins and ingredients.

[The perl code](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/lib/ProductOpener/Tags.pm#L1157):
```perl
	# For the origins taxonomy, include the countries taxonomy
	if ($tagtype eq "origins") {
		@files = ("countries", "origins");
	}

	# For the Open Food Facts ingredients taxonomy, concatenate additives, minerals, vitamins, nucleotides and other nutritional substances taxonomies
	elsif (($tagtype eq "ingredients") and (defined $options{product_type}) and ($options{product_type} eq "food")) {
		@files = (
			"additives_classes", "additives", "minerals", "vitamins",
			"nucleotides", "other_nutritional_substances", "ingredients"
		);
	}

	# Packaging
	elsif (($tagtype eq "packaging")) {
		@files = ("packaging_materials", "packaging_shapes", "packaging_recycling", "preservation");
	}

	# Traces - just a copy of allergens
	elsif ($tagtype eq "traces") {
		@files = ("allergens");
	}
```

Proposed solution:

* add a pragma in taxonomies to tell external taxonomies to load, or put it in the taxonomy editor code ?
* parse files as done in perl code, but marking external entries with a property external
* do not enable edition on those entries and signal which taxonomy they are from

**Comment by perierc** [comment]
@alexgarel I've just remembered that we removed the `countries` taxonomy from the importable taxonomies because there were too much errors, so not sure what to do for `origins` 🤔

**Comment by alexgarel** [comment]
We can eventually remove origins for now. Most of the time those are generated taxonomies (from other sources)
