### ISSUE TITLE
Do not run api service as root

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#63]
Currently the Fast API service is running as root, it should not:

- introduce a user in backend/Dockerfile
- this user should use the USER_UID parameter to get right uid

**Comment by alexgarel** [comment]
Please look at the way we do it in repositories like https://github.com/openfoodfacts/robotoff/ to keep consisten.

**Comment by alexgarel** [comment]
This ticket should be treated after https://github.com/openfoodfacts/taxonomy-editor/pull/105 and https://github.com/openfoodfacts/taxonomy-editor/pull/106 are merged.

@Aju100, are you interested ?

**Comment by Aju100** [comment]
Sure @alexgarel I would love to get hands dirty on this
