### ISSUE TITLE
Implement taxonomy import from github

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#71]
- [x] modify parser library to add a labels parameter, that add labels on every nodes (we will use it for branch_name and taxonomy name)
- [x] add an UI to create a project by specifying a new branch name, a taxonomy to import and a description
- [x] add an API point that create a project importing a taxonomy from github (part of it is in #83)

**Comment by aadarsh-ram** [comment]
All tasks done. Closed via #101
