### ISSUE TITLE
Children and new node id should be normalized in the backend

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#79]
We have an API to add an entry or add children introduced by #76 

This API do not currently normalize the tag used as ID, it should.

Normalization function is currently in the Parser. If possible it should be moved to a utility function and called from the backend to normalize received id.

**Comment by aerial-ace1** [comment]
Can I work on this issue?

**Comment by aadarsh-ram** [comment]
@aerial-ace1 Please do! I'll assign this issue to you.
