### ISSUE TITLE
Add an API to add a new project

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/taxonomy-editor#83]
Add an API point to create a new project.

- A project has a name (aka branch name) and a taxonomy to work on, it has to be unique.
- it also have a free description field
- taxonomy value should match one of available taxonomies in Open Food Facts.
- the status is "new"
- It creates a node with label PROJECT and with property description, branch_name, taxonomy and status

**Comment by aadarsh-ram** [comment]
Closed via #116
